export const PRODUCTS_ACTION_TYPES = {
  FETCH_PRODUCTS_START: "products/SET_PRODUCTS_START",
  FETCH_PRODUCTS_SUCCESS: "products/SET_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_FAILED: "products/SET_PRODUCTS_FAILED",
};
